# build me
# docker build -t westonplatter/ruby-nodejs-postgres:2.3.1 -f Dockerfile-ruby-2.3.1 .

# push me
# docker push westonplatter/ruby-nodejs-postgres:2.3.1

FROM ruby:2.3.1

RUN apt-get update -qq \
  && apt-get install -y \
    build-essential \
    libpq-dev \
    ruby-dev \
    zlib1g-dev \
    liblzma-dev \
    libxslt-dev \
    libxml2-dev \
    locales

RUN curl -sL https://deb.nodesource.com/setup_4.x | bash -
RUN apt-get install -y nodejs

RUN npm install -g phantomjs-prebuilt
