FROM ruby:2.4.1

RUN apt-get update -qq \
  && apt-get install -y \
    build-essential \
    ruby-dev \
    zlib1g-dev \
    liblzma-dev \
    libxslt-dev \
    libxml2-dev \
    locales \
    libpq-dev

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs

RUN npm install -g phantomjs-prebuilt
RUN npm install -g webpack
