FROM ruby:2.7.2

RUN apt-get update -qq \
  && apt-get install -y \
    build-essential \
    ruby-dev \
    zlib1g-dev \
    liblzma-dev \
    libxslt-dev \
    libxml2-dev \
    locales \
    libpq-dev \
    postgresql-client

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs

RUN npm install -g phantomjs-prebuilt --unsafe-perm
RUN npm install -g webpack
RUN npm install -g yarn
