FROM ruby:2.3.1

LABEL maintainer gwestonplatter@gmail.com

RUN apt-get update -qq \
  && apt-get install -y \
    build-essential \
    libmysqlclient-dev \
    ruby-dev \
    zlib1g-dev \
    liblzma-dev \
    libxslt-dev \
    libxml2-dev \
    locales

RUN curl -sL https://deb.nodesource.com/setup_4.x | bash -
RUN apt-get install -y nodejs
