Skip to content
This repository
Search
Pull requests
Issues
Marketplace
Gist
 @westonplatter
 Sign out
 Watch 0
  Star 0
 Fork 0 westonplatter/dockerfiles
 Code  Issues 0  Pull requests 0  Projects 0  Wiki  Settings Insights
Branch: ruby-nodejs-po… Find file Copy pathdockerfiles/ruby-nodejs-mysql/Dockerfile-ruby-2.3.1
f5c7f90  9 days ago
 Weston Platter ruby-nodejs-mysql ruby 2.4.0 and nodejs 6.x
0 contributors
RawBlameHistory
48 lines (40 sloc)  1018 Bytes
# build me
# docker build -t westonplatter/ruby-nodejs-mysql:2.3.1 -f Dockerfile-ruby-2.3.1 .

# push me
# docker push westonplatter/ruby-nodejs-mysql:2.3.1

FROM ruby:2.3.1

# all
RUN apt-get update -qq \
  && apt-get install -y \
    build-essential \
    ruby-dev \
    zlib1g-dev \
    liblzma-dev \
    libxslt-dev \
    libxml2-dev \
    locales \
    libmysqlclient-dev

# node
RUN apt-get install -y \
  python \
  python-dev \
  python-pip \
  python-virtualenv

# cleanup
RUN rm -rf /var/lib/apt/lists/*

# install nodejs
RUN \
  cd /tmp && \
  wget http://nodejs.org/dist/node-latest.tar.gz && \
  tar xvzf node-latest.tar.gz && \
  rm -f node-latest.tar.gz && \
  cd node-v* && \
  ./configure && \
  CXX="g++ -Wno-unused-local-typedefs" make && \
  CXX="g++ -Wno-unused-local-typedefs" make install && \
  cd /tmp && \
  rm -rf /tmp/node-v* && \
  npm install -g npm && \
  echo '\n# Node.js\nexport PATH="node_modules/.bin:$PATH"' >> /root/.bashrc

# node/phantomjs
RUN npm install -g phantomjs-prebuilt
Contact GitHub API Training Shop Blog About
© 2017 GitHub, Inc. Terms Privacy Security Status Help
